--
-- Dumping data for table `#__projectlog_projects`
--



--
-- Dumping data for table `#__content_types`
--

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `rules`, `field_mappings`, `router`, `content_history_options`) VALUES
('Projectlog Project', 'com_projectlog.project', '{"special": {"dbtable": "#__projectlog_projects", "key": "id", "type": "Project", "prefix": "ProjectlogTable", "config": "array()"}, "common": {"dbtable": "#__ucm_content", "key": "ucm_id", "type": "Corecontent", "prefix": "JTable", "config": "array()"', '', '{"common": {"core_content_item_id": "id", "core_title": "name", "core_state": "published", "core_alias": "alias", "core_created_time": "created", "core_modified_time": "modified", "core_body": "misc", "core_hits": "null", "core_publish_up": "publish_up",  "core_publish_down": "publish_down",  "core_access": "access",  "core_params": "params",  "core_featured": "null", "core_metadata": "metadata", "core_language": "language", "core_images": "image", "core_version": "version", "core_ordering": "ordering", "core_metakey": "metakey", "core_metadesc": "metadesc", "core_catid": "catid", "core_xreference": "null", "asset_id": "null"},"special": {}}', 'ProjectlogHelperRoute::getProjectRoute', '{"formFile": "administrator/components/com_projectlog/models/forms/project.xml", "hideFields": [ "checked_out", "checked_out_time", "version", "reset"],"ignoreChanges": [  "modified_by",  "modified",  "checked_out",  "checked_out_time",  "version",  "imptotal",  "impmade",  "reset"],"convertToInt": [ "publish_up",  "publish_down",  "ordering"],"displayLookup": [  {    "sourceColumn": "catid",    "targetTable": "#__categories",    "targetColumn": "id",    "displayColumn": "title"  },  {    "sourceColumn": "created_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name" },  {    "sourceColumn": "modified_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name"  }]}'),
('Projectlog Category', 'com_projectlog.category', '{"special":{"dbtable":"#__categories","key":"id","type":"Category","prefix":"JTable","config":"array()"},"common":{"dbtable":"#__ucm_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":{"core_content_item_id":"id","core_title":"title","core_state":"published","core_alias":"alias","core_created_time":"created_time","core_modified_time":"modified_time","core_body":"description", "core_hits":"hits","core_publish_up":"null","core_publish_down":"null","core_access":"access", "core_params":"params", "core_featured":"null", "core_metadata":"metadata", "core_language":"language", "core_images":"null", "core_urls":"null", "core_version":"version", "core_ordering":"null", "core_metakey":"metakey", "core_metadesc":"metadesc", "core_catid":"parent_id", "core_xreference":"null", "asset_id":"asset_id"}, "special":{"parent_id":"parent_id","lft":"lft","rgt":"rgt","level":"level","path":"path","extension":"extension","note":"note"}}', '', '{"formFile":"administrator/components/com_categories/models/forms/category.xml", "hideFields":["checked_out","checked_out_time","version","lft","rgt","level","path","extension"], "ignoreChanges":["modified_user_id", "modified_time", "checked_out", "checked_out_time", "version", "hits", "path"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"created_user_id","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}, {"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_user_id","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"parent_id","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"}]}'),
('Projectlog Log', 'com_projectlog.log', '{"special": {"dbtable": "#__projectlog_logs", "key": "id", "type": "Log", "prefix": "ProjectlogTable", "config": "array()"}, "common": {"dbtable": "#__ucm_content", "key": "ucm_id", "type": "Corecontent", "prefix": "JTable", "config": "array()"', '', '{"common": {"core_content_item_id": "id", "core_title": "title", "core_state": "published", "core_alias": "alias", "core_created_time": "created", "core_modified_time": "modified", "core_body": "misc", "core_hits": "null", "core_publish_up": "publish_up",  "core_publish_down": "publish_down",  "core_access": "access",  "core_params": "params",  "core_featured": "null", "core_metadata": "metadata", "core_language": "language", "core_images": "image", "core_version": "version", "core_ordering": "ordering", "core_metakey": "metakey", "core_metadesc": "metadesc", "core_catid": "catid", "core_xreference": "null", "asset_id": "null"},"special": {}}', '', '{"formFile": "administrator/components/com_projectlog/models/forms/log.xml", "hideFields": [ "checked_out", "checked_out_time", "version", "reset"],"ignoreChanges": [  "modified_by",  "modified",  "checked_out",  "checked_out_time",  "version",  "imptotal",  "impmade",  "reset"],"convertToInt": [ "publish_up",  "publish_down",  "ordering"],"displayLookup": [  {    "sourceColumn": "catid",    "targetTable": "#__categories",    "targetColumn": "id",    "displayColumn": "title"  },  {    "sourceColumn": "created_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name" },  {    "sourceColumn": "modified_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name"  }]}'),
('Projectlog Doc', 'com_projectlog.doc', '{"special": {"dbtable": "#__projectlog_docs", "key": "id", "type": "Doc", "prefix": "ProjectlogTable", "config": "array()"}, "common": {"dbtable": "#__ucm_content", "key": "ucm_id", "type": "Corecontent", "prefix": "JTable", "config": "array()"', '', '{"common": {"core_content_item_id": "id", "core_title": "title", "core_state": "published", "core_alias": "alias", "core_created_time": "created", "core_modified_time": "modified", "core_body": "misc", "core_hits": "null", "core_publish_up": "publish_up",  "core_publish_down": "publish_down",  "core_access": "access",  "core_params": "params",  "core_featured": "null", "core_metadata": "metadata", "core_language": "language", "core_images": "image", "core_version": "version", "core_ordering": "ordering", "core_metakey": "metakey", "core_metadesc": "metadesc", "core_catid": "catid", "core_xreference": "null", "asset_id": "null"},"special": {}}', '', '{"formFile": "administrator/components/com_projectlog/models/forms/doc.xml", "hideFields": [ "checked_out", "checked_out_time", "version", "reset"],"ignoreChanges": [  "modified_by",  "modified",  "checked_out",  "checked_out_time",  "version",  "imptotal",  "impmade",  "reset"],"convertToInt": [ "publish_up",  "publish_down",  "ordering"],"displayLookup": [  {    "sourceColumn": "catid",    "targetTable": "#__categories",    "targetColumn": "id",    "displayColumn": "title"  },  {    "sourceColumn": "created_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name" },  {    "sourceColumn": "modified_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name"  }]}');