--
-- Dumping data for table `#__projectlog_projects`
--

INSERT INTO `#__projectlog_projects` (`catid`, `access`, `job_id`, `release_id`, `task_id`, `workorder_id`, `name`, `alias`, `misc`, `release_date`, `contract_from`, `contract_to`, `specific_loc`, `general_loc`, `manager`, `chief`, `technicians`, `deployment_from`, `deployment_to`, `onsite`, `project_type`, `client`, `status`, `approved`, `image`, `imagepos`, `email_to`, `default_con`, `published`, `checked_out`, `checked_out_time`, `ordering`, `params`, `mobile`, `webpage`, `sortname1`, `sortname2`, `sortname3`, `language`, `created`, `created_by`, `created_by_alias`, `modified`, `modified_by`, `metakey`, `metadesc`, `metadata`, `featured`, `xreference`, `publish_up`, `publish_down`, `version`, `hits`) VALUES
(1, 1, '86958JID', '345555RID', '34', '2342311WOID', 'Sample Project', 'sample-project', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nisi sed magna vehicula dapibus quis at mauris. Etiam auctor nunc vitae orci porttitor, sed pharetra eros placerat. Maecenas convallis vulputate iaculis. Etiam eget eleifend turpis. Vestibulum euismod at dolor eget auctor. Etiam ut consectetur odio, eget consectetur metus. Proin eget odio id magna convallis interdum. Nulla iaculis non eros at lacinia. Duis laoreet malesuada est posuere mollis.</p>\r\n\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nisi sed magna vehicula dapibus quis at mauris. Etiam auctor nunc vitae orci porttitor, sed pharetra eros placerat. Maecenas convallis vulputate iaculis. Etiam eget eleifend turpis. Vestibulum euismod at dolor eget auctor. Etiam ut consectetur odio, eget consectetur metus. Proin eget odio id magna convallis interdum. Nulla iaculis non eros at lacinia. Duis laoreet malesuada est posuere mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at nisi sed magna vehicula dapibus quis at mauris. Etiam auctor nunc vitae orci porttitor, sed pharetra eros placerat. Maecenas convallis vulputate iaculis. Etiam eget eleifend turpis. Vestibulum euismod at dolor eget auctor. Etiam ut consectetur odio, eget consectetur metus. Proin eget odio id magna convallis interdum. Nulla iaculis non eros at lacinia. Duis laoreet malesuada est posuere mollis.</p>', '2014-07-17 14:03:17', '2014-07-01 14:03:00', '2014-07-31 14:03:00', '23444 E. Greenbluff. Here are directions from CDA.\r\n\r\nTake I-90 freeway W\r\nTake Argonne Exit\r\nGo until you get there', 'Near Green Bluff Washington', '570', 570, 'Bob Franklin - Carpenter, Sally Johnson - Interior Decorator', '2014-07-18 14:03:40', '2014-07-22 14:03:44', 1, 'Construction', 'My Client', '', 1, 'images/joomla_logo_black.jpg', NULL, 'test@example.com', 0, 1, 0, '0000-00-00 00:00:00', 1, '{"show_project_category":"","show_project_list":"","presentation_style":"","show_tags":"","show_name":"","show_manager":"","show_email":"","show_street_address":"","show_project_type":"","show_client":"","show_job_id":"","show_release_id":"","show_task_id":"","show_mobile":"","show_workorder_id":"","show_webpage":"","show_misc":"","show_image":"","allow_vcard":"","show_articles":"","show_profile":"","show_links":"","linka_name":"","linka":false,"linkb_name":"","linkb":false,"linkc_name":"","linkc":false,"linkd_name":"","linkd":false,"linke_name":"","linke":"","project_layout":"","show_email_form":"","show_email_copy":"","banned_email":"","banned_subject":"","banned_text":"","validate_session":"","custom_reply":"","redirect":""}', '555-965-9854', 'http://thethinkery.net', '', '', '', '*', '2014-07-17 21:05:10', 570, '', '2014-07-17 22:57:05', 570, '', '', '{"robots":"","rights":""}', 1, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 18, 0);

--
-- Dumping data for table `#__content_types`
--

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `rules`, `field_mappings`, `router`, `content_history_options`) VALUES
('Projectlog Project', 'com_projectlog.project', '{"special": {"dbtable": "#__projectlog_projects", "key": "id", "type": "Projectlog", "prefix": "ProjectlogTable", "config": "array()"}, "common": {"dbtable": "#__ucm_content", "key": "ucm_id", "type": "Corecontent", "prefix": "JTable", "config": "array()"', '', '{"common": {"core_content_item_id": "id", "core_title": "name", "core_state": "published", "core_alias": "alias", "core_created_time": "created", "core_modified_time": "modified", "core_body": "misc", "core_hits": "null", "core_publish_up": "publish_up",  "core_publish_down": "publish_down",  "core_access": "access",  "core_params": "params",  "core_featured": "null", "core_metadata": "metadata", "core_language": "language", "core_images": "image", "core_version": "version", "core_ordering": "ordering", "core_metakey": "metakey", "core_metadesc": "metadesc", "core_catid": "catid", "core_xreference": "null", "asset_id": "null"},"special": {}}', 'ProjectlogHelperRoute::getProjectRoute', '{"formFile": "administrator/components/com_projectlog/models/forms/project.xml", "hideFields": [ "checked_out", "checked_out_time", "version", "reset"],"ignoreChanges": [  "modified_by",  "modified",  "checked_out",  "checked_out_time",  "version",  "imptotal",  "impmade",  "reset"],"convertToInt": [ "publish_up",  "publish_down",  "ordering"],"displayLookup": [  {    "sourceColumn": "catid",    "targetTable": "#__categories",    "targetColumn": "id",    "displayColumn": "title"  },  {    "sourceColumn": "created_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name" },  {    "sourceColumn": "modified_by",    "targetTable": "#__users",    "targetColumn": "id",    "displayColumn": "name"  }]}'),
('Projectlog Category', 'com_projectlog.category', '{"special":{"dbtable":"#__categories","key":"id","type":"Category","prefix":"JTable","config":"array()"},"common":{"dbtable":"#__ucm_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":{"core_content_item_id":"id","core_title":"title","core_state":"published","core_alias":"alias","core_created_time":"created_time","core_modified_time":"modified_time","core_body":"description", "core_hits":"hits","core_publish_up":"null","core_publish_down":"null","core_access":"access", "core_params":"params", "core_featured":"null", "core_metadata":"metadata", "core_language":"language", "core_images":"null", "core_urls":"null", "core_version":"version", "core_ordering":"null", "core_metakey":"metakey", "core_metadesc":"metadesc", "core_catid":"parent_id", "core_xreference":"null", "asset_id":"asset_id"}, "special":{"parent_id":"parent_id","lft":"lft","rgt":"rgt","level":"level","path":"path","extension":"extension","note":"note"}}', '', '{"formFile":"administrator/components/com_categories/models/forms/category.xml", "hideFields":["checked_out","checked_out_time","version","lft","rgt","level","path","extension"], "ignoreChanges":["modified_user_id", "modified_time", "checked_out", "checked_out_time", "version", "hits", "path"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"created_user_id","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}, {"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_user_id","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"parent_id","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"}]}');
